import fs from 'fs';
import path from 'path';

const MINIFIED_LINE_LENGTH = 500;
const MINIFIED_AVERAGE_LINE_LENGTH = 200;
const MINIFIED_NEWLINE_RATIO = 0.005;

function normalizePath(filename) {
  return filename.replace(/\\/g, '/').toLowerCase();
}

function basename(filename) {
  return path.basename(filename).toLowerCase();
}

function sourceMapReference(content) {
  const match = content.match(/[#@]\s*sourceMappingURL=([^\s]+)/);
  return match ? match[1] : null;
}

function normalizeVirtualPath(filename) {
  return filename.replace(/\\/g, '/').replace(/^\/+/, '');
}

function isPathInsideRoot(relativePath) {
  return relativePath !== '' && relativePath !== '..' && !relativePath.startsWith(`..${path.sep}`) && !path.isAbsolute(relativePath);
}

function classificationPath(filename, options = {}) {
  if (options.targetRelativePath)
    return normalizeVirtualPath(options.targetRelativePath);

  if (options.scannerRoot) {
    try {
      const relativePath = path.relative(path.resolve(options.scannerRoot), path.resolve(filename));
      if (isPathInsideRoot(relativePath))
        return normalizeVirtualPath(relativePath);
    } catch (error) {
      return filename;
    }
  }

  return filename;
}

function sourceMapCandidates(filename, reference) {
  if (!reference || /^data:/i.test(reference))
    return [];

  if (path.isAbsolute(reference))
    return [reference];

  const joined = path.join(path.dirname(filename), reference);
  const resolved = path.resolve(path.dirname(filename), reference);
  const candidates = [joined, resolved];

  return [...new Set(candidates)];
}

function sourceMapExistsWithLoader(filename, reference, options) {
  if (!options.sourceMapExists)
    return false;

  try {
    return sourceMapCandidates(filename, reference).some(candidate => options.sourceMapExists(candidate, {
      filename,
      reference
    }));
  } catch (error) {
    return false;
  }
}

function sourceMapExistsInFileList(filename, reference, options) {
  if (!options.availableFiles)
    return false;

  const files = options.availableFiles instanceof Set ? options.availableFiles : new Set(options.availableFiles);
  const normalizedFiles = new Set([...files].map(normalizeVirtualPath));

  return sourceMapCandidates(filename, reference).some(candidate => normalizedFiles.has(normalizeVirtualPath(candidate)));
}

function externalSourceMapExists(filename, reference, options = {}) {
  if (!reference || /^data:/i.test(reference))
    return false;

  if (sourceMapExistsWithLoader(filename, reference, options) || sourceMapExistsInFileList(filename, reference, options))
    return true;

  try {
    return fs.existsSync(path.resolve(path.dirname(filename), reference));
  } catch (error) {
    return false;
  }
}

function hasAdjacentSourceMap(filename, options = {}) {
  if (sourceMapExistsWithLoader(filename, `${path.basename(filename)}.map`, options) || sourceMapExistsInFileList(filename, `${path.basename(filename)}.map`, options))
    return true;

  try {
    return fs.existsSync(`${filename}.map`);
  } catch (error) {
    return false;
  }
}

function isLikelyMinified(filename, content) {
  const name = basename(filename);
  if (/\.(min|prod|production)\.(js|css)$/i.test(name))
    return true;

  const lines = content.split(/\r?\n/);
  const nonEmptyLines = lines.filter(line => line.trim().length > 0);
  const longestLine = nonEmptyLines.reduce((max, line) => Math.max(max, line.length), 0);
  const averageLineLength = nonEmptyLines.length === 0 ? 0 : content.length / nonEmptyLines.length;
  const newlineRatio = content.length === 0 ? 0 : (lines.length - 1) / content.length;

  return longestLine >= MINIFIED_LINE_LENGTH ||
    (content.length >= 1000 && averageLineLength >= MINIFIED_AVERAGE_LINE_LENGTH && newlineRatio <= MINIFIED_NEWLINE_RATIO);
}

function isLikelyBundle(filename, content) {
  const normalized = normalizePath(filename);
  const name = basename(filename);

  return /(^|[\/._-])(bundle|chunk|webpack|rollup|browserify|vendor)([\/._-]|$)/i.test(normalized) ||
    /\.(bundle|chunk)\.js$/i.test(name) ||
    /webpackJsonp|__webpack_require__|webpackChunk|parcelRequire|rollupPluginBabelHelpers/.test(content);
}

function isVendorOrGenerated(filename, content) {
  const normalized = normalizePath(filename);

  return /(^|\/)(node_modules|bower_components|vendor|vendors|third_party|third-party|generated|gen|dist|build|out|coverage)(\/|$)/.test(normalized) ||
    /@generated|<auto-generated|automatically generated|code generated by|do not edit/i.test(content.slice(0, 4096));
}

export function classifyFile(filename, content, options = {}) {
  content = content ? content.toString() : '';
  const fileForHeuristics = classificationPath(filename, options);
  const reference = sourceMapReference(content);
  const inlineSourceMap = reference ? /^data:/i.test(reference) : false;
  const externalSourceMap = externalSourceMapExists(filename, reference, options);
  const adjacentSourceMap = hasAdjacentSourceMap(filename, options);

  return {
    is_minified: isLikelyMinified(fileForHeuristics, content),
    is_bundle: isLikelyBundle(fileForHeuristics, content),
    vendor_or_generated: isVendorOrGenerated(fileForHeuristics, content),
    source_map_present: Boolean(reference || adjacentSourceMap),
    source_map_available: inlineSourceMap || externalSourceMap || adjacentSourceMap,
    source_map_reference: reference,
    parser_status: options.parserStatus || 'unparsed',
    parser: options.parser || null,
    source_type: options.sourceType,
    parse_error: options.parseError || null
  };
}

export function parseErrorRecord(filename, classification, error) {
  classification = classification || {};
  const parserStatus = classification.parser_status || 'error';

  return {
    file: filename,
    message: error.message,
    line: error.loc ? error.loc.line : error.lineNumber,
    column: error.loc ? error.loc.column : error.column,
    parser_status: parserStatus,
    file_classification: {
      is_minified: classification.is_minified || false,
      is_bundle: classification.is_bundle || false,
      vendor_or_generated: classification.vendor_or_generated || false,
      source_map_present: classification.source_map_present || false,
      source_map_available: classification.source_map_available || false,
      parser_status: parserStatus
    }
  };
}
